"use client";
import { sendChat } from "@/lib/chat-client";
import { ChatWorkspace,ModelMenu } from "@/components/chat-workspace";
import { DropdownMenu,DropdownMenuContent,DropdownMenuTrigger,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuLabel } from "@/components/ui/dropdown-menu";
import { MoreHorizontal,Settings2,SquarePen,ChevronUp } from "lucide-react";
import { useState,useEffect,useCallback,useRef } from "react";
import { MessageSquare,Database,ChartNoAxesCombined,Plus,ArrowUp,BookOpen,Search,Pencil,Trash2,FileText,ExternalLink,Download,RefreshCw,LogOut } from "lucide-react";
import { Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuAction,SidebarTrigger,useSidebar } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from "@/components/ui/sheet";
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from "@/components/ui/table";
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { catalog,keysOf,Row } from "@/lib/catalog";
type Tables=Record<string,Row[]>;
type Stats={bots:Row[];knowledge:Row[];documents:Row[];daily:Row[];coverage:{assistants:number;cited:number}};
async function api(url:string,method="GET",data?:unknown){const r=await fetch(url,{method,headers:method==="GET"?{}:{"Content-Type":"application/json"},body:data?JSON.stringify(data):undefined});const j:any=await r.json();if(!r.ok)throw Object.assign(new Error(j.error||"操作失敗"),{status:r.status});return j;}
function Picker({value,onChange,items,label,disabled=false}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function SideAction({children,onClick,active=false}:{children:React.ReactNode;onClick:()=>void;active?:boolean}){const{setOpenMobile}=useSidebar();return <SidebarMenuButton isActive={active} onClick={()=>{onClick();setOpenMobile(false)}}>{children}</SidebarMenuButton>}
function WorkspaceMenu({onNavigate}:{onNavigate:(view:string)=>void}){const{setOpenMobile}=useSidebar();const go=(view:string)=>{onNavigate(view);setOpenMobile(false)};return <DropdownMenu><DropdownMenuTrigger asChild><button className="workspace-menu"><Settings2 size={18}/><span>工作空間</span><ChevronUp size={15}/></button></DropdownMenuTrigger><DropdownMenuContent side="top" align="start" className="workspace-dropdown"><DropdownMenuItem onSelect={()=>go("data")}><Database/>資料管理</DropdownMenuItem><DropdownMenuItem onSelect={()=>go("stats")}><ChartNoAxesCombined/>統計</DropdownMenuItem><DropdownMenuItem onSelect={()=>go("design")}><BookOpen/>資料庫設計</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
export default function Home(){
 const[tables,setTables]=useState<Tables>({}),[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[error,setError]=useState("");
 const[view,setView]=useState("chat"),[selected,setSelected]=useState(""),[draft,setDraftState]=useState(""),[bot,setBot]=useState(""),[profile,setProfile]=useState<Row|null>(null),[busy,setBusy]=useState(false);
 const[table,setTable]=useState("KnowledgeBase"),[search,setSearch]=useState(""),[historySearch,setHistorySearch]=useState(""),[stats,setStats]=useState<Stats|null>(null);
 const[edit,setEdit]=useState<{table:string;row:Row|null}|null>(null),[form,setForm]=useState<Row>({}),[formError,setFormError]=useState("");
 const[remove,setRemove]=useState<{table:string;row:Row}|null>(null),[source,setSource]=useState<Row|null>(null);
 const[pending,setPending]=useState<{id:string;content:string;answer?:string}|null>(null),[sendError,setSendError]=useState<{id:string;message:string}|null>(null);
 const drafts=useRef<Record<string,string>>({}),selectedRef=useRef(""),viewRef=useRef("chat"),sendingRef=useRef(false);
 const setDraft=(text:string)=>{drafts.current[selectedRef.current]=text;setDraftState(text)};

 const rows=(t:string)=>tables[t]??[];
 const refresh=useCallback(async()=>{try{const data=await api("/api/data");setTables(data.tables);setProfile(data.user);setAuth(false);setError("");return data.tables as Tables;}catch(e:any){if(e.status===401)setAuth(true);else setError(e.message);throw e;}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh().catch(()=>{})},[refresh]); useEffect(()=>{if(auth)window.location.replace("/login")},[auth]);
 useEffect(()=>{if(!bot&&tables.Chatbot?.length)setBot(String((tables.Chatbot.find(b=>b.bot_id==="bot-deepseek-flash")||tables.Chatbot[0]).bot_id));},[tables,bot]);
 const navigate=(v:string,id="",keepDraft=false)=>{const old=selectedRef.current;if(keepDraft)drafts.current[id]=drafts.current[old]||"";selectedRef.current=id;viewRef.current=v;setView(v);setSelected(id);setDraftState(drafts.current[id]||"");history.pushState({},"",v==="chat"?(id?`/?conversation=${encodeURIComponent(id)}`:"/"):`/?view=${v}`)};
 useEffect(()=>{const read=()=>{const p=new URLSearchParams(location.search),v=p.get("view")||"chat",id=p.get("conversation")||"";selectedRef.current=id;viewRef.current=v;setView(["chat","data","stats","design"].includes(v)?v:"chat");setSelected(id);setDraftState(drafts.current[id]||"")};read();window.addEventListener("popstate",read);return()=>window.removeEventListener("popstate",read)},[]);
 useEffect(()=>{if(view==="stats")api("/api/stats").then(setStats).catch(e=>toast.error(e.message));},[view,tables]);
 const conv=rows("Conversation").find(c=>c.conversation_id===selected);
 const messages=rows("Message").filter(m=>m.conversation_id===selected).sort((a,b)=>Number(a.message_no)-Number(b.message_no));
 const currentBot=rows("Chatbot").find(b=>b.bot_id===(conv?.bot_id||bot));
 const chooseModel=(id:string)=>{if(id===String(conv?.bot_id||bot))return;setBot(id);if(conv){navigate("chat");toast("已切換模型，開始新對話")}};

 const display=(ref:string,id:string|number)=>{const s=catalog[ref];const r=rows(ref).find(x=>x[s.pk[0]]===id);return String(r?.name||r?.title||id)};
 const newForm=(t:string,row:Row|null=null)=>{setFormError("");const value:Row=row?{...row}:{};if(!row)for(const f of catalog[t].fields){if(f.auto)continue;value[f.key]=f.kind==="number"?1:f.options?.[0]||"";if(f.ref&&rows(f.ref).length)value[f.key]=rows(f.ref)[0][catalog[f.ref].pk[0]];}if(!row&&t==="Chatbot")value.model_name="deepseek-flash";setForm(value);setEdit({table:t,row})};
 const save=async()=>{if(!edit)return;setBusy(true);setFormError("");try{await api("/api/records",edit.row?"PUT":"POST",{table:edit.table,values:form,keys:edit.row?keysOf(edit.table,edit.row):undefined});await refresh();setEdit(null);toast.success("已儲存");}catch(e:any){setFormError(e.message)}finally{setBusy(false)}};
 const deleteRow=async()=>{if(!remove)return;setBusy(true);try{await api("/api/records","DELETE",{table:remove.table,keys:keysOf(remove.table,remove.row)});if(remove.table==="Conversation"){const deleted=String(remove.row.conversation_id);delete drafts.current[deleted];if(selectedRef.current===deleted)navigate("chat");setSendError(prev=>prev?.id===deleted?null:prev);}await refresh();setRemove(null);toast.success("已刪除")}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const seed=async()=>{setBusy(true);try{await api("/api/seed","POST",{});await refresh();toast.success("已加入示範資料")}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const send=async()=>{
  const content=draft.trim();if(!content||sendingRef.current||busy||!profile||!bot)return;
  sendingRef.current=true;setSendError(null);setDraft("");let id=selected;setPending({id,content});
  try{
   if(!id){const result=await api("/api/records","POST",{table:"Conversation",values:{bot_id:bot,title:content.slice(0,50)}});id=String(result.record.conversation_id);setTables(prev=>({...prev,Conversation:[...(prev.Conversation||[]),result.record]}));setPending({id,content});if(selectedRef.current===""&&viewRef.current==="chat")navigate("chat",id,true);}
   const result=await sendChat(id,content,token=>setPending(prev=>prev?{...prev,answer:(prev.answer||"")+token}:prev));
   setTables(prev=>({...prev,Message:[...(prev.Message||[]).filter(m=>m.conversation_id!==id),...result.messages],MessageCitation:[...(prev.MessageCitation||[]).filter(m=>m.conversation_id!==id),...result.references]}));
  }catch(e:any){
   if(e.status===401){setAuth(true);return;}
   // Reconcile a possibly committed response before offering another send.
   let saved=false;try{const fresh=await refresh();saved=(fresh.Message||[]).some(m=>m.conversation_id===id&&m.role==="user"&&m.content===content&&Number(m.message_no)>Math.max(0,...messages.map(m=>Number(m.message_no))))}catch{}
   if(!saved){if(!drafts.current[id])drafts.current[id]=content;if(selectedRef.current===id)setDraftState(drafts.current[id]);setSendError({id,message:e.message});}
  }finally{sendingRef.current=false;setPending(null)}
 };
 const exportRows=()=>{const content=JSON.stringify(filtered,null,2);const u=URL.createObjectURL(new Blob([content],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=`${table}.json`;a.click();URL.revokeObjectURL(u)};
 const filtered=rows(table).filter(row=>Object.values(row).some(v=>String(v).toLowerCase().includes(search.toLowerCase())));
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:"search_chat_records",title:"查詢資料",description:"查詢目前資料表並更新畫面，不修改資料。",inputSchema:{type:"object",properties:{table:{type:"string",enum:Object.keys(catalog)},query:{type:"string",maxLength:200}},required:["table","query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||!catalog[input.table]||typeof input.query!=="string"||input.query.length>200)throw new Error("查詢條件不正確");const data=await refresh();setTable(input.table);setSearch(input.query);setView("data");history.pushState({},"","/?view=data");return{records:data[input.table].filter(r=>Object.values(r).some(v=>String(v).includes(input.query))).slice(0,50)}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[refresh]);
 const noData=!loading&&!auth&&!error&&!rows("Chatbot").length;
 return <SidebarProvider><Sidebar className="chat-sidebar"><SidebarHeader><div className="side-brand"><img className="brand-logo" src="/ghat-cpt-logo.png" alt="" width={32} height={32}/><b>GhatCPT</b><SidebarTrigger className="ml-auto"/></div><SidebarMenu><SidebarMenuItem><SideAction onClick={()=>navigate("chat")}><SquarePen/><span>新對話</span></SideAction></SidebarMenuItem></SidebarMenu><div className="history-search"><Search size={16}/><Input aria-label="搜尋對話" placeholder="搜尋對話" value={historySearch} onChange={e=>setHistorySearch(e.target.value)}/></div></SidebarHeader><SidebarContent><div className="history-label">你的對話</div><SidebarMenu>{[...rows("Conversation")].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).filter(c=>String(c.title).toLowerCase().includes(historySearch.toLowerCase())).map(c=><SidebarMenuItem key={c.conversation_id} className="history-item"><SideAction active={view==="chat"&&selected===c.conversation_id} onClick={()=>navigate("chat",String(c.conversation_id))}><span>{c.title}</span></SideAction><DropdownMenu><DropdownMenuTrigger asChild><SidebarMenuAction aria-label={`對話選單：${c.title}`} disabled={!!pending||busy}><MoreHorizontal size={16}/></SidebarMenuAction></DropdownMenuTrigger><DropdownMenuContent side="right" align="start"><DropdownMenuItem onSelect={()=>newForm("Conversation",c)}><Pencil/>重新命名</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem variant="destructive" onSelect={()=>setRemove({table:"Conversation",row:c})}><Trash2/>刪除對話</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarMenuItem>)}</SidebarMenu>{loading?<div className="px-5 space-y-3"><Skeleton className="h-8"/><Skeleton className="h-8"/></div>:<p className="history-empty">{!rows("Conversation").length?"尚無對話":historySearch&&!rows("Conversation").some(c=>String(c.title).toLowerCase().includes(historySearch.toLowerCase()))?"找不到對話":""}</p>}</SidebarContent><SidebarFooter><WorkspaceMenu onNavigate={navigate}/><DropdownMenu><DropdownMenuTrigger asChild><button className="side-account" aria-label="帳號選單"><span className="avatar">{String(profile?.name||"G").slice(0,1).toUpperCase()}</span><span className="account-name">{profile?.name||"載入中"}</span><MoreHorizontal size={17}/></button></DropdownMenuTrigger><DropdownMenuContent side="top" align="start" className="account-menu"><DropdownMenuLabel>{profile?.name}<small>{profile?.email}</small></DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem asChild><a href="/signout-with-chatgpt?return_to=/login" target="_top"><LogOut/>登出</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar>
 <main className={`app-main ${view==="chat"?"chat-main":""}`}><header className="app-header"><div className="header-left"><SidebarTrigger/>{view==="chat"?<ModelMenu bots={rows("Chatbot").filter(b=>b.bot_id==="bot-deepseek-flash")} value="bot-deepseek-flash" onChange={chooseModel} disabled={loading||!!pending||!rows("Chatbot").length}/>:<strong>{view==="data"?"資料管理":view==="stats"?"統計":"資料庫設計"}</strong>}</div><div className="header-actions">{view!=="chat"&&<Button variant="ghost" onClick={()=>navigate("chat")}><MessageSquare size={17}/>返回對話</Button>}{view==="chat"&&<Button variant="ghost" size="icon" aria-label="新對話" onClick={()=>navigate("chat")}><SquarePen size={20}/></Button>}{conv&&view==="chat"&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="對話選單" disabled={!!pending}><MoreHorizontal size={20}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>newForm("Conversation",conv)}><Pencil/>重新命名</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem variant="destructive" onSelect={()=>setRemove({table:"Conversation",row:conv})}><Trash2/>刪除對話</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div></header>
 {auth?<Empty><EmptyHeader><EmptyTitle>登入後繼續</EmptyTitle></EmptyHeader><Button asChild><a href="/login">前往登入</a></Button></Empty>:<>
 {error&&<div role="alert" className="error-banner">{error}<Button variant="ghost" onClick={()=>refresh().catch(()=>{})}>重試</Button></div>}
 {view==="chat"&&<ChatWorkspace id={selected} messages={messages} references={rows("MessageCitation")} documents={rows("Document")} draft={draft} setDraft={setDraft} onSend={send} onSource={setSource} loading={loading} disabled={busy||!!pending||!profile} pending={pending} noModels={noData} onSeed={seed} seeding={busy} modelName={String(currentBot?.name||"")} modelId={String(currentBot?.model_name||"")} sendError={sendError?.id===selected?sendError.message:""} onClearError={()=>setSendError(null)}/>}
 {view==="data"&&<div className="management"><div className="data-toolbar"><Picker label="資料表" value={table} onChange={v=>{setTable(v);setSearch("")}} items={Object.entries(catalog).map(([value,c])=>({value,label:c.label}))}/><div className="record-search"><Search size={17}/><Input aria-label="搜尋資料" placeholder="搜尋資料" value={search} onChange={e=>setSearch(e.target.value)}/></div>{table!=="User"&&<Button onClick={()=>newForm(table)}><Plus size={16}/>新增</Button>}<Button variant="outline" onClick={exportRows} aria-label="匯出查詢結果"><Download size={16}/></Button></div><div className="table-heading"><h1>{catalog[table].label}</h1><span>{filtered.length} 筆</span>{noData&&<Button variant="outline" disabled={busy} onClick={seed}>載入示範資料</Button>}</div><div className="data-table"><Table><TableHeader><TableRow>{catalog[table].fields.map(f=><TableHead key={f.key}>{f.label}</TableHead>)}<TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((r,i)=><TableRow key={i}>{catalog[table].fields.map(f=><TableCell key={f.key}><span className={`cell-text ${f.auto?"mono":""}`} title={String(r[f.key]??"")}>{f.ref?display(f.ref,r[f.key]):String(r[f.key]??"")}</span></TableCell>)}<TableCell><div className="row-actions">{table!=="User"&&!catalog[table].fields.every(f=>catalog[table].pk.includes(f.key))&&<Button variant="ghost" size="icon" aria-label={`編輯第 ${i+1} 筆`} onClick={()=>newForm(table,r)}><Pencil size={16}/></Button>}{table==="Document"&&<Button variant="ghost" size="icon" aria-label={`查看第 ${i+1} 筆文件`} onClick={()=>setSource(r)}><FileText size={16}/></Button>}{table!=="User"&&<Button variant="ghost" size="icon" aria-label={`刪除第 ${i+1} 筆`} onClick={()=>setRemove({table,row:r})}><Trash2 size={16}/></Button>}</div></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<Empty><EmptyHeader><EmptyTitle>{search?"找不到資料":"尚無資料"}</EmptyTitle></EmptyHeader></Empty>}</div></div>}
 {view==="stats"&&<div className="management"><h1>使用統計</h1>{!stats?<Skeleton className="h-64"/>:<><div className="metric-grid">{[["對話",rows("Conversation").length],["訊息",rows("Message").length],["文件",rows("Document").length],["助理引用率",stats.coverage.assistants?`${Math.round(stats.coverage.cited/stats.coverage.assistants*100)}%`:"—"]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="stats-grid"><section className="stats-panel"><h2>機器人對話量</h2>{stats.bots.map(b=><div className="bar-row" key={b.bot_id}><div><span>{b.name}</span><b>{b.conversations}</b></div><div className="bar-track"><div style={{width:`${Number(b.conversations)/Math.max(1,...stats.bots.map(x=>Number(x.conversations)))*100}%`}}/></div></div>)}</section><section className="stats-panel"><h2>文件引用排行</h2>{stats.documents.map((d,i)=><div className="ranking" key={`${d.kb_id}-${d.document_no}`}><span>{i+1}</span><b>{d.title}</b><span>{d.citations} 次</span></div>)}</section><section className="stats-panel"><h2>知識庫使用量</h2><Table><TableHeader><TableRow><TableHead>知識庫</TableHead><TableHead>文件</TableHead><TableHead>引用</TableHead></TableRow></TableHeader><TableBody>{stats.knowledge.map(k=><TableRow key={k.kb_id}><TableCell>{k.name}</TableCell><TableCell>{k.documents}</TableCell><TableCell>{k.citations}</TableCell></TableRow>)}</TableBody></Table></section><section className="stats-panel"><h2>每日訊息量</h2><Table><TableHeader><TableRow><TableHead>日期 UTC</TableHead><TableHead>訊息</TableHead></TableRow></TableHeader><TableBody>{stats.daily.map(d=><TableRow key={d.day}><TableCell>{d.day}</TableCell><TableCell>{d.messages}</TableCell></TableRow>)}</TableBody></Table></section></div></>}</div>}
 {view==="design"&&<div className="management design-view"><h1>資料庫設計</h1><div className="design-links"><a href="/reference/erd.png" target="_blank" rel="noreferrer">ERD <ExternalLink size={15}/></a><a href="/reference/schema.png" target="_blank" rel="noreferrer">關聯綱目 <ExternalLink size={15}/></a></div><Table><TableHeader><TableRow><TableHead>資料表</TableHead><TableHead>主鍵</TableHead><TableHead>筆數</TableHead></TableRow></TableHeader><TableBody>{Object.entries(catalog).map(([t,c])=><TableRow key={t}><TableCell>{t}<small>{c.label}</small></TableCell><TableCell className="mono">{c.pk.join(" + ")}</TableCell><TableCell>{rows(t).length}</TableCell></TableRow>)}</TableBody></Table><img src="/reference/erd.png" alt="Chatbot 系統 ERD，包含六個實體與兩個多對多關係"/></div>}
 </>}
 </main>
 <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!busy)setEdit(null)}}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>{edit?.row?"編輯":"新增"}{edit?catalog[edit.table].singular:""}</DialogTitle><DialogDescription className="sr-only">填寫欄位後儲存。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save()}}><div className="form-fields">{edit&&catalog[edit.table].fields.filter(f=>!f.auto&&!(edit.table==="Conversation"&&(f.key==="user_id"||!!edit.row&&f.key==="bot_id"))).map(f=><label key={f.key} className="field"><span>{f.label}{f.optional&&<small>選填</small>}</span>{f.ref?<Picker label={f.label} value={String(form[f.key]||"")} onChange={v=>setForm({...form,[f.key]:v})} disabled={!!edit.row&&catalog[edit.table].pk.includes(f.key)} items={rows(f.ref).map(r=>({value:String(r[catalog[f.ref!].pk[0]]),label:String(r.name||r.title||r[catalog[f.ref!].pk[0]])}))}/>:f.options?<Picker label={f.label} value={String(form[f.key]||"")} onChange={v=>setForm({...form,[f.key]:v})} items={f.options.map(x=>({value:x,label:x}))}/>:f.kind==="long"?<Textarea aria-label={f.label} required={!f.optional} value={String(form[f.key]??"")} onChange={e=>setForm({...form,[f.key]:e.target.value})} maxLength={20000} rows={5}/>:<Input aria-label={f.label} type={f.kind==="number"?"number":f.kind==="email"?"email":f.kind==="url"?"url":"text"} min={f.kind==="number"?1:undefined} required={!f.optional} maxLength={300} disabled={!!edit.row&&catalog[edit.table].pk.includes(f.key)} value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div>{formError&&<p className="form-error" role="alert">{formError}</p>}<DialogFooter><Button variant="outline" type="button" disabled={busy} onClick={()=>setEdit(null)}>取消</Button><Button disabled={busy} type="submit">{busy?"儲存中…":"儲存"}</Button></DialogFooter></form></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={open=>{if(!open&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{remove?.table==="Conversation"?"刪除對話？":"刪除這筆資料？"}</AlertDialogTitle><AlertDialogDescription>{remove?.table==="Conversation"?`「${remove.row.title}」的訊息與引用將一併刪除，無法復原。`:"刪除後無法復原。"}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={deleteRow}>刪除</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Sheet open={!!source} onOpenChange={open=>{if(!open)setSource(null)}}><SheetContent className="source-sheet"><SheetHeader><SheetTitle>{source?.title}</SheetTitle><SheetDescription>{source?display("KnowledgeBase",source.kb_id):""}</SheetDescription></SheetHeader><div className="source-body"><p>{source?.content}</p>{source?.source_url&&/^https?:\/\//.test(String(source.source_url))?<a href={String(source.source_url)} target="_blank" rel="noreferrer">開啟來源 <ExternalLink size={16}/></a>:null}<small>{source?.kb_id} / {source?.document_no}</small></div></SheetContent></Sheet>
 <Toaster position="bottom-right"/></SidebarProvider>
}



